apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
